### ISSUE TITLE
HTML Comments

### ISSUE THREAD

**Issue by cyouh95** [mihneam/prj-rev-bwfs-dasmoto#1]
For making comments in HTML, it should actually be 2 hyphens (`--`) instead of 3:
```html
<!-- Write your comments here -->
```

https://github.com/mihneam/prj-rev-bwfs-dasmoto/blob/5a3c3662ceeaa712abc711712b442f65df1f5f07/Dasmotos/index.html#L12

**Comment by mihneam** [comment]
Ah fair enough, will keep in mind! Thanks!
