### ISSUE TITLE
font-size property

### ISSUE THREAD

**Issue by cyouh95** [mihneam/prj-rev-bwfs-dasmoto#2]
Setting `font-size: 100px` for your `div.header` element is actually different than setting `font-size: 100px` for the `h1` element inside the `div`. In the former (the way you currently have it), the `font-size` for the `h1` element is actually `200px` because by default, the `font-size` for `h1` elements is `2em` (2 x 100px = 200px).

Here is a good resource on this: https://css-tricks.com/almanac/properties/f/font-size/#article-header-id-3

https://github.com/mihneam/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/style.css#L7
https://github.com/mihneam/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L14-L16

**Comment by mihneam** [comment]
Ah right - thanks! That makes sense. I was wondering why that was, assumed it might just be a responsive thing that we haven't covered yet.

So then would an appropriate fix be just to specify font-size for h1 as 1em? So we'd have:

```
.header h1 {
  font-size: 1em;
}
```

**Comment by cyouh95** [comment]
Yup! Or even easier, you could specify `font-size: 100px` for `.header h1`, and omit the `font-size` property for the `div` container.

**Comment by mihneam** [comment]
Ah, got it! Thanks very much!
