### ISSUE TITLE
Great job linking image files

### ISSUE THREAD

**Issue by cyouh95** [mihneam/prj-rev-bwfs-dasmoto#4]
Nice job linking image files in both your stylesheet and HTML document!

https://github.com/mihneam/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/style.css#L6
https://github.com/mihneam/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L22

**Comment by mihneam** [comment]
Thank you!
