### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [mihneam/prj-rev-bwfs-dasmoto#5]
(Exceeds Expectations)

Nicely done on this project! It looks like you have a solid understanding of how HTML and CSS work together for display of content. And great job with the use of classes and IDs for selecting and styling your elements! (#3) 

Continue to explore the way CSS properties and their inheritance work. (For example, #2 - just little things that you will pick up as you work on the projects!)

As a further challenge, try creating your own page from scratch without the use of any specs or template. You definitely already have a good sense of how to organize and structure your code - this will be great practice for continuing to build your skills!

**Comment by mihneam** [comment]
Thanks for your feedback!

This project was actually quite a good overview of how inheritance works, as I found myself simplifying the rules several times - it's always best to see that stuff in action.

Cheers for pointing things out on the other tickets, have responded on each one.

Will have a play with building more stuff from scratch all throughout, of course...
